# Generated by Django 6.1.1 on 2026-09-14 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('play', '0001_initial'),
        ('theatrehall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('show_time', models.DateTimeField(help_text='Date and time of the performance')),
                ('play', models.ForeignKey(help_text='Play being performed', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='play.play')),
                ('theatre_hall', models.ForeignKey(help_text='Theatre hall where the performance takes place', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='theatrehall.theatrehall')),
            ],
            options={
                'verbose_name': 'performance',
                'verbose_name_plural': 'performances',
                'ordering': ['show_time'],
            },
        ),
    ]
