# Generated by Django 6.1.1 on 2026-09-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('name', models.CharField(help_text='Theatre hall name', max_length=100, unique=True)),
                ('rows', models.PositiveIntegerField(help_text='Number of rows in the theatre hall')),
                ('seats_in_row', models.PositiveIntegerField(help_text='Number of seats in each row')),
            ],
            options={
                'verbose_name': 'Theatre Hall',
                'verbose_name_plural': 'Theatre Halls',
                'ordering': ['name'],
            },
        ),
    ]
