# Generated by Django 6.1.1 on 2026-09-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('name', models.CharField(help_text='Genre name', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('first_name', models.CharField(db_index=True, help_text='Actor first name', max_length=100)),
                ('last_name', models.CharField(db_index=True, help_text='Actor last name', max_length=100)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_actor_name')],
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('title', models.CharField(help_text='Play title', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Play description')),
                ('actors', models.ManyToManyField(blank=True, related_name='plays', to='play.actor')),
                ('genres', models.ManyToManyField(blank=True, related_name='plays', to='play.genre')),
            ],
            options={
                'verbose_name': 'Play',
                'verbose_name_plural': 'Plays',
                'ordering': ['title'],
            },
        ),
    ]
