# Generated by Django 6.1.1 on 2026-09-17 09:57

import play.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(db_index=True, help_text='Actor first name', max_length=100, validators=[play.validators.name_validator]),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(db_index=True, help_text='Actor last name', max_length=100, validators=[play.validators.name_validator]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Genre name', max_length=100, unique=True, validators=[play.validators.genre_name_validator]),
        ),
        migrations.AlterField(
            model_name='play',
            name='description',
            field=models.TextField(blank=True, help_text='Play description', max_length=2000),
        ),
    ]
