# Generated by Django 6.1.1 on 2026-09-14 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(help_text='User who made the reservation', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='performance',
            field=models.ForeignKey(help_text='Performance for which the ticket is issued', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='performance.performance'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(help_text='Reservation associated with the ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket.reservation'),
        ),
    ]
